trigger:
  - dev
  - test
  - acc
  - production

jobs:
  - job: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: "10.x"
      displayName: "Install Node.js"

    - script: npm config set "@fortawesome:registry" https://npm.fontawesome.com/ && npm config set "//npm.fontawesome.com/:_authToken" $(fa_token)
      displayName: "FA token"
    - script: npm install
      displayName: "Install dependencies"
    - script: REACT_APP_API_ENV=$(Build.SourceBranchName)
      displayName: "Set env"
    - script: npm run-script prod:build
      displayName: "Build"
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: $(System.DefaultWorkingDirectory)/build
        ArtifactName: BuildedApp