trigger:
- dev
- test
- acc
- production


pool:
  vmImage: 'windows-latest'

extends:
  template: azure-pipelines-template.yml
  parameters:
    env: "dev"
    target_store: "obfrontenddev"
    fa-token: $(fa_token)