name: CI/CD

on:
  push:
    branches: [dev, feature/ci]
  pull_request:
    branches: [dev, feature/ci]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
          
    env:
        REACT_APP_API_VERSION: v0.1
        REACT_APP_API_ENV: dev
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run the tests and generate coverage report
        run: npm test -- --coverage --ci

      - name: Build
        run: npm run build
